OltCfg:
  base_oid_1 : ".1.3.6.1.4.1.3902.1082"
  base_oid_2 : ".1.3.6.1.4.1.3902.1012"
  onu_id_name : ".500.10.2.3.3.1.2"
  onu_type: ".3.50.11.2.1.17"

Board1Pon1:
  onu_id_name: ".500.10.2.3.3.1.2.285278465"
  onu_type: ".3.50.11.2.1.17.268501248"
  onu_serial_number: ".500.10.2.3.3.1.18.285278465"
  onu_rx_power: ".500.20.2.2.2.1.10.285278465"
  onu_tx_power: ".3.50.12.1.1.14.268501248"
  onu_status_id: ".500.10.2.3.8.1.4.285278465"
  onu_ip_address: ".3.50.16.1.1.10.268501248"
  onu_description: ".500.10.2.3.3.1.3.285278465"
  onu_last_online_time: ".500.10.2.3.8.1.5.285278465"
  onu_last_offline_time: ".500.10.2.3.8.1.6.285278465"
  onu_last_offline_reason: ".500.10.2.3.8.1.7.285278465"
  onu_gpon_optical_distance: ".500.10.2.3.10.1.2.285278465"

Board1Pon2:
  onu_id_name: ".500.10.2.3.3.1.2.285278466"
  onu_type: ".3.50.11.2.1.17.268501504"
  onu_serial_number: ".500.10.2.3.3.1.18.285278466"
  onu_rx_power: ".500.20.2.2.2.1.10.285278466"
  onu_tx_power: ".3.50.12.1.1.14.268501504"
  onu_status_id: ".500.10.2.3.8.1.4.285278466"
  onu_ip_address: ".3.50.16.1.1.10.268501504"
  onu_description: ".500.10.2.3.3.1.3.285278466"
  onu_last_online_time: ".500.10.2.3.8.1.5.285278466"
  onu_last_offline_time: ".500.10.2.3.8.1.6.285278466"
  onu_last_offline_reason: ".500.10.2.3.8.1.7.285278466"
  onu_gpon_optical_distance: ".500.10.2.3.10.1.2.285278466"

Board1Pon3:
  onu_id_name: ".500.10.2.3.3.1.2.285278467"
  onu_type: ".3.50.11.2.1.17.268501760"
  onu_serial_number: ".500.10.2.3.3.1.18.285278467"
  onu_rx_power: ".500.20.2.2.2.1.10.285278467"
  onu_tx_power: ".3.50.12.1.1.14.268501760"
  onu_status_id: ".500.10.2.3.8.1.4.285278467"
  onu_ip_address: ".3.50.16.1.1.10.268501760"
  onu_description: ".500.10.2.3.3.1.3.285278467"
  onu_last_online_time: ".500.10.2.3.8.1.5.285278467"
  onu_last_offline_time: ".500.10.2.3.8.1.6.285278467"
  onu_last_offline_reason: ".500.10.2.3.8.1.7.285278467"
  onu_gpon_optical_distance: ".500.10.2.3.10.1.2.285278467"

Board1Pon4:
  onu_id_name: ".500.10.2.3.3.1.2.285278468"
  onu_type: ".3.50.11.2.1.17.268502016"
  onu_serial_number: ".500.10.2.3.3.1.18.285278468"
  onu_rx_power: ".500.20.2.2.2.1.10.285278468"
  onu_tx_power: ".3.50.12.1.1.14.268502016"
  onu_status_id: ".500.10.2.3.8.1.4.285278468"
  onu_ip_address: ".3.50.16.1.1.10.268502016"
  onu_description: ".500.10.2.3.3.1.3.285278468"
  onu_last_online_time: ".500.10.2.3.8.1.5.285278468"
  onu_last_offline_time: ".500.10.2.3.8.1.6.285278468"
  onu_last_offline_reason: ".500.10.2.3.8.1.7.285278468"
  onu_gpon_optical_distance: ".500.10.2.3.10.1.2.285278468"


Board1Pon5:
  onu_id_name: ".500.10.2.3.3.1.2.285278469"
  onu_type: ".3.50.11.2.1.17.268502272"
  onu_serial_number: ".500.10.2.3.3.1.18.285278469"
  onu_rx_power: ".500.20.2.2.2.1.10.285278469"
  onu_tx_power: ".3.50.12.1.1.14.268502272"
  onu_status_id: ".500.10.2.3.8.1.4.285278469"
  onu_ip_address: ".3.50.16.1.1.10.268502272"
  onu_description: ".500.10.2.3.3.1.3.285278469"
  onu_last_online_time: ".500.10.2.3.8.1.5.285278469"
  onu_last_offline_time: ".500.10.2.3.8.1.6.285278469"
  onu_last_offline_reason: ".500.10.2.3.8.1.7.285278469"
  onu_gpon_optical_distance: ".500.10.2.3.10.1.2.285278469"

Board1Pon6:
  onu_id_name: ".500.10.2.3.3.1.2.285278470"
  onu_type: ".3.50.11.2.1.17.268502528"
  onu_serial_number: ".500.10.2.3.3.1.18.285278470"
  onu_rx_power: ".500.20.2.2.2.1.10.285278470"
  onu_tx_power: ".3.50.12.1.1.14.268502528"
  onu_status_id: ".500.10.2.3.8.1.4.285278470"
  onu_ip_address: ".3.50.16.1.1.10.268568064"
  onu_description: ".500.10.2.3.3.1.3.285278470"
  onu_last_online_time: ".500.10.2.3.8.1.5.285278470"
  onu_last_offline_time: ".500.10.2.3.8.1.6.285278470"
  onu_last_offline_reason: ".500.10.2.3.8.1.7.285278470"
  onu_gpon_optical_distance: ".500.10.2.3.10.1.2.285278470"

Board1Pon7:
  onu_id_name: ".500.10.2.3.3.1.2.285278471"
  onu_type: ".3.50.11.2.1.17.268502784"
  onu_serial_number: ".500.10.2.3.3.1.18.285278471"
  onu_rx_power: ".500.20.2.2.2.1.10.285278471"
  onu_tx_power: ".3.50.12.1.1.14.268502784"
  onu_status_id: ".500.10.2.3.8.1.4.285278471"
  onu_ip_address: ".3.50.16.1.1.10.268502528"
  onu_description: ".500.10.2.3.3.1.3.285278471"
  onu_last_online_time: ".500.10.2.3.8.1.5.285278471"
  onu_last_offline_time: ".500.10.2.3.8.1.6.285278471"
  onu_last_offline_reason: ".500.10.2.3.8.1.7.285278471"
  onu_gpon_optical_distance: ".500.10.2.3.10.1.2.285278471"

Board1Pon8:
  onu_id_name: ".500.10.2.3.3.1.2.285278472"
  onu_type: ".3.50.11.2.1.17.268503040"
  onu_serial_number: ".500.10.2.3.3.1.18.285278472"
  onu_rx_power: ".500.20.2.2.2.1.10.285278472"
  onu_tx_power: ".3.50.12.1.1.14.268503040"
  onu_status_id: ".500.10.2.3.8.1.4.285278472"
  onu_ip_address: ".3.50.16.1.1.10.268503040"
  onu_description: ".500.10.2.3.3.1.3.285278472"
  onu_last_online_time: ".500.10.2.3.8.1.5.285278472"
  onu_last_offline_time: ".500.10.2.3.8.1.6.285278472"
  onu_last_offline_reason: ".500.10.2.3.8.1.7.285278472"
  onu_gpon_optical_distance: ".500.10.2.3.10.1.2.285278472"

Board2Pon1:
  onu_id_name: ".500.10.2.3.3.1.2.285278721"
  onu_type: ".3.50.11.2.1.17.268566784"
  onu_serial_number: ".500.10.2.3.3.1.18.285278721"
  onu_rx_power: ".500.20.2.2.2.1.10.285278721"
  onu_tx_power: ".3.50.12.1.1.14.268566784"
  onu_status_id: ".500.10.2.3.8.1.4.285278721"
  onu_ip_address: ".3.50.16.1.1.10.268566784"
  onu_description: ".500.10.2.3.3.1.3.285278721"
  onu_last_online_time: ".500.10.2.3.8.1.5.285278721"
  onu_last_offline_time: ".500.10.2.3.8.1.6.285278721"
  onu_last_offline_reason: ".500.10.2.3.8.1.7.285278721"
  onu_gpon_optical_distance: ".500.10.2.3.10.1.2.285278721"

Board2Pon2:
  onu_id_name: ".500.10.2.3.3.1.2.285278722"
  onu_type: ".3.50.11.2.1.17.268567040"
  onu_serial_number: ".500.10.2.3.3.1.18.285278722"
  onu_rx_power: ".500.20.2.2.2.1.10.285278722"
  onu_tx_power: ".3.50.12.1.1.14.268567040"
  onu_status_id: ".500.10.2.3.8.1.4.285278722"
  onu_ip_address: ".3.50.16.1.1.10.268567040"
  onu_description: ".500.10.2.3.3.1.3.285278722"
  onu_last_online_time: ".500.10.2.3.8.1.5.285278722"
  onu_last_offline_time: ".500.10.2.3.8.1.6.285278722"
  onu_last_offline_reason: ".500.10.2.3.8.1.7.285278722"
  onu_gpon_optical_distance: ".500.10.2.3.10.1.2.285278722"

Board2Pon3:
  onu_id_name: ".500.10.2.3.3.1.2.285278723"
  onu_type: ".3.50.11.2.1.17.268567296"
  onu_serial_number: ".500.10.2.3.3.1.18.285278723"
  onu_rx_power: ".500.20.2.2.2.1.10.285278723"
  onu_tx_power: ".3.50.12.1.1.14.268567296"
  onu_status_id: ".500.10.2.3.8.1.4.285278723"
  onu_ip_address: ".3.50.16.1.1.10.268567296"
  onu_description: ".500.10.2.3.3.1.3.285278723"
  onu_last_online_time: ".500.10.2.3.8.1.5.285278723"
  onu_last_offline_time: ".500.10.2.3.8.1.6.285278723"
  onu_last_offline_reason: ".500.10.2.3.8.1.7.285278723"
  onu_gpon_optical_distance: ".500.10.2.3.10.1.2.285278723"


Board2Pon4:
  onu_id_name: ".500.10.2.3.3.1.2.285278724"
  onu_type: ".3.50.11.2.1.17.268567552"
  onu_serial_number: ".500.10.2.3.3.1.18.285278724"
  onu_rx_power: ".500.20.2.2.2.1.10.285278724"
  onu_tx_power: ".3.50.12.1.1.14.268567552"
  onu_status_id: ".500.10.2.3.8.1.4.285278724"
  onu_ip_address: ".3.50.16.1.1.10.268567552"
  onu_description: ".500.10.2.3.3.1.3.285278724"
  onu_last_online_time: ".500.10.2.3.8.1.5.285278724"
  onu_last_offline_time: ".500.10.2.3.8.1.6.285278724"
  onu_last_offline_reason: ".500.10.2.3.8.1.7.285278724"
  onu_gpon_optical_distance: ".500.10.2.3.10.1.2.285278724"


Board2Pon5:
  onu_id_name: ".500.10.2.3.3.1.2.285278725"
  onu_type: ".3.50.11.2.1.17.268567808"
  onu_serial_number: ".500.10.2.3.3.1.18.285278725"
  onu_rx_power: ".500.20.2.2.2.1.10.285278725"
  onu_tx_power: ".3.50.12.1.1.14.268567808"
  onu_status_id: ".500.10.2.3.8.1.4.285278725"
  onu_ip_address: ".3.50.16.1.1.10.268567808"
  onu_description: ".500.10.2.3.3.1.3.285278725"
  onu_last_online_time: ".500.10.2.3.8.1.5.285278725"
  onu_last_offline_time: ".500.10.2.3.8.1.6.285278725"
  onu_last_offline_reason: ".500.10.2.3.8.1.7.285278725"
  onu_gpon_optical_distance: ".500.10.2.3.10.1.2.285278725"

Board2Pon6:
  onu_id_name: ".500.10.2.3.3.1.2.285278726"
  onu_type: ".3.50.11.2.1.17.268568064"
  onu_serial_number: ".500.10.2.3.3.1.18.285278726"
  onu_rx_power: ".500.20.2.2.2.1.10.285278726"
  onu_tx_power: ".3.50.12.1.1.14.268568064"
  onu_status_id: ".500.10.2.3.8.1.4.285278726"
  onu_ip_address: ".3.50.16.1.1.10.268568064"
  onu_description: ".500.10.2.3.3.1.3.285278726"
  onu_last_online_time: ".500.10.2.3.8.1.5.285278726"
  onu_last_offline_time: ".500.10.2.3.8.1.6.285278726"
  onu_last_offline_reason: ".500.10.2.3.8.1.7.285278726"
  onu_gpon_optical_distance: ".500.10.2.3.10.1.2.285278726"

Board2Pon7:
  onu_id_name: ".500.10.2.3.3.1.2.285278727"
  onu_type: ".3.50.11.2.1.17.268568320"
  onu_serial_number: ".500.10.2.3.3.1.18.285278727"
  onu_rx_power: ".500.20.2.2.2.1.10.285278727"
  onu_tx_power: ".3.50.12.1.1.14.268568320"
  onu_status_id: ".500.10.2.3.8.1.4.285278727"
  onu_ip_address: ".3.50.16.1.1.10.268568320"
  onu_description: ".500.10.2.3.3.1.3.285278727"
  onu_last_online_time: ".500.10.2.3.8.1.5.285278727"
  onu_last_offline_time: ".500.10.2.3.8.1.6.285278727"
  onu_last_offline_reason: ".500.10.2.3.8.1.7.285278727"
  onu_gpon_optical_distance: ".500.10.2.3.10.1.2.285278727"


Board2Pon8:
  onu_id_name: ".500.10.2.3.3.1.2.285278728"
  onu_type: ".3.50.11.2.1.17.268568576"
  onu_serial_number: ".500.10.2.3.3.1.18.285278728"
  onu_rx_power: ".500.20.2.2.2.1.10.285278728"
  onu_tx_power: ".3.50.12.1.1.14.268568576"
  onu_status_id: ".500.10.2.3.8.1.4.285278728"
  onu_ip_address: ".3.50.16.1.1.10.268568576"
  onu_description: ".500.10.2.3.3.1.3.285278728"
  onu_last_online_time: ".500.10.2.3.8.1.5.285278728"
  onu_last_offline_time: ".500.10.2.3.8.1.6.285278728"
  onu_last_offline_reason: ".500.10.2.3.8.1.7.285278728"
  onu_gpon_optical_distance: ".500.10.2.3.10.1.2.285278728"
